name: Build SQLite3 shell
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64
    - name: Download SQLite source code
      run: |
        curl "https://sqlite.org/2022/sqlite-amalgamation-3400100.zip" -o sqlite-amalgamation.zip
        unzip sqlite-amalgamation.zip -dsqlite-tmp
        mkdir sqlite-src
        for f in 'sqlite-tmp/*'; do mv $f/* sqlite-src/; done
        patch -ui sqlite-shell-unicode.patch sqlite-src/shell.c
      shell: bash
    - name: Build sqlite3.exe
      run: |
        cd sqlite-src
        cl /nologo /W3 /O2 /MD /EHs-c- /GR- /GS /GL /GF /Gy /Zi shell.c sqlite3.c /link /nologo /time /out:sqlite3.exe /dynamicbase:no /nxcompat /ltcg /opt:icf /opt:ref /PDBALTPATH:"%_PDB%"
    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: sqlite3
        path: |
          sqlite-src/sqlite3.exe
          sqlite-src/sqlite3.pdb
